# Generated by Django 4.0 on 2022-02-01 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SiteAdmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareAttention',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='SiteAdmin.transaction')),
                ('motive', models.CharField(max_length=200, verbose_name='Motivo de Consulta')),
                ('diagnosis', models.CharField(max_length=200, verbose_name='Diagnóstico')),
                ('treatment', models.CharField(max_length=200, verbose_name='Tratamiento')),
            ],
            bases=('SiteAdmin.transaction',),
        ),
    ]
