# Generated by Django 4.0 on 2022-02-11 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareAttention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('motive', models.CharField(default='', max_length=200, verbose_name='Motivo de Consulta')),
                ('diagnosis', models.CharField(default='', max_length=200, verbose_name='Diagnóstico')),
                ('treatment', models.CharField(default='', max_length=200, verbose_name='Tratamiento')),
                ('pet_id', models.IntegerField(null=True)),
                ('vet_id', models.IntegerField(null=True)),
                ('veterinarian_id', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sender_user_id', models.IntegerField(null=True)),
                ('receiver_user_id', models.IntegerField(null=True)),
                ('message', models.CharField(default='', max_length=500, verbose_name='Mensaje')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
