# Generated by Django 4.0 on 2022-02-05 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareAttention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(default='', max_length=20, verbose_name='Tipo de Transacción')),
                ('motive', models.CharField(default='', max_length=200, verbose_name='Motivo de Consulta')),
                ('diagnosis', models.CharField(default='', max_length=200, verbose_name='Diagnóstico')),
                ('treatment', models.CharField(default='', max_length=200, verbose_name='Tratamiento')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
