# Generated by Django 4.0 on 2022-02-01 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SiteAdmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='SiteAdmin.employee')),
            ],
            bases=('SiteAdmin.employee',),
        ),
        migrations.CreateModel(
            name='Vet',
            fields=[
                ('company_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='SiteAdmin.company')),
            ],
            bases=('SiteAdmin.company',),
        ),
        migrations.CreateModel(
            name='Veterinarian',
            fields=[
                ('employee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='SiteAdmin.employee')),
                ('license', models.CharField(max_length=11, verbose_name='Licencia')),
            ],
            bases=('SiteAdmin.employee',),
        ),
    ]
