# Generated by Django 4.0 on 2022-02-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyVet', '0002_alter_employee_birthdate_alter_vet_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='birthdate',
            field=models.DateField(default='', verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='vet',
            name='start_date',
            field=models.DateField(default='', verbose_name='Fecha de Inscripción'),
        ),
        migrations.AlterField(
            model_name='veterinarian',
            name='birthdate',
            field=models.DateField(default='', verbose_name='Fecha de Nacimiento'),
        ),
    ]
