# Generated by Django 4.0 on 2022-02-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyVet', '0004_alter_employee_birthdate_alter_vet_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vet',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='veterinarian',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
