# Generated by Django 4.0 on 2022-02-10 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyVet', '0005_employee_user_id_vet_user_id_veterinarian_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='company_id',
        ),
        migrations.RemoveField(
            model_name='veterinarian',
            name='company_id',
        ),
        migrations.AddField(
            model_name='employee',
            name='vet_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='veterinarian',
            name='vet_id',
            field=models.IntegerField(null=True),
        ),
    ]
