# Generated by Django 4.0 on 2022-02-01 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SiteAdmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daddy',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='SiteAdmin.person')),
            ],
            bases=('SiteAdmin.person',),
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('animal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='SiteAdmin.animal')),
                ('nickname', models.CharField(max_length=50, verbose_name='Nombre')),
                ('birthdate', models.DateField(verbose_name='01/01/1990')),
                ('buddy', models.IntegerField()),
            ],
            bases=('SiteAdmin.animal',),
        ),
    ]
