# Generated by Django 4.0 on 2022-02-11 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Daddy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('person_id', models.CharField(default='', max_length=8, verbose_name='DNI')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Nombre')),
                ('surname', models.CharField(default='', max_length=50, verbose_name='Apellido')),
                ('birthdate', models.DateField(null=True, verbose_name='Fecha de Nacimiento')),
                ('address', models.CharField(default='', max_length=100, verbose_name='Domicilio')),
                ('phone', models.CharField(default='', max_length=20, verbose_name='Teléfono')),
                ('cellphone', models.CharField(default='', max_length=20, verbose_name='Celular')),
                ('mail', models.EmailField(default='info@mail.com', max_length=254)),
                ('user_id', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('species', models.CharField(default='', max_length=50, null=True, verbose_name='Especie')),
                ('family', models.CharField(default='', max_length=50, null=True, verbose_name='Familia')),
                ('race', models.CharField(default='', max_length=50, null=True, verbose_name='Raza')),
                ('color', models.CharField(default='', max_length=50, null=True, verbose_name='Color')),
                ('nickname', models.CharField(default='', max_length=50, verbose_name='Nombre')),
                ('birthdate', models.DateField(null=True, verbose_name='Fecha de Nacimiento')),
                ('daddy_id', models.IntegerField()),
                ('vet_id', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
