# Generated by Django 4.0 on 2022-02-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyDaddy', '0004_alter_daddy_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='vet_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='birthdate',
            field=models.DateField(null=True, verbose_name='Fecha de Nacimiento'),
        ),
    ]
