# Generated by Django 4.0 on 2022-02-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyDaddy', '0005_pet_vet_id_alter_pet_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='color',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='description',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='family',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='Familia'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='race',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='Raza'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='Especie'),
        ),
    ]
