# Generated by Django 4.0 on 2022-02-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyDaddy', '0006_alter_pet_color_alter_pet_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='daddy',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
