# Generated by Django 4.0 on 2022-02-06 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyDaddy', '0008_rename_buddy_id_pet_daddy_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='description',
        ),
    ]
