# Generated by Django 4.0 on 2022-02-01 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SiteAdmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='entity_ptr',
        ),
        migrations.RemoveField(
            model_name='company',
            name='entity_ptr',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='person_ptr',
        ),
        migrations.RemoveField(
            model_name='person',
            name='entity_ptr',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='Animal',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Entity',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
